name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build ward.elf
      run: make -j
    - name: Upload ward.elf
      uses: actions/upload-artifact@v1
      with:
        name: ward.elf
        path: output/ward.elf
    - name: Install mtools
      run: sudo apt-get update && sudo apt-get install -y mtools
    - name: Build disk images
      run: make -j disks
    - name: Upload disk images
      uses: actions/upload-artifact@v1
      with:
        name: disks
        path: |
          output/ward.img
          output/ward.vhdx
          output/ward.vmdk
          output/ward.vdi
    - name: Install QEMU
      run: sudo apt-get install -y qemu-system-x86
    - name: Unit tests
      run: make qemu-test
