name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build kernel.elf
      run: make -j
    - name: Upload kernel.elf
      uses: actions/upload-artifact@v1
      with:
        name: kernel.elf
        path: o.qemu/kernel.elf
    - name: Install mtools
      run: sudo apt-get update && sudo apt-get install -y mtools
    - name: Build boot.img
      run: make -j o.qemu/boot.img
    - name: Upload boot.img
      uses: actions/upload-artifact@v1
      with:
        name: boot.img
        path: o.qemu/boot.img
    - name: Install QEMU
      run: sudo apt-get install -y qemu-system-x86
    - name: Unit tests
      run: make QEMUACCEL= qemu-test

  macos:
    runs-on: macos-10.15
    steps:
    - run: pwd
      working-directory: ${{ runner.temp }}
    - run: curl -O https://github.com/macports/macports-base/releases/download/v2.6.2/MacPorts-2.6.2-10.15-Catalina.pkg
      working-directory: ${{ runner.temp }}
    - run: ls -l $(pwd)/MacPorts-2.6.2-10.15-Catalina.pkg
      working-directory: ${{ runner.temp }}
    - run: sudo ls -l $(pwd)/MacPorts-2.6.2-10.15-Catalina.pkg
      working-directory: ${{ runner.temp }}
    - run: sudo /usr/sbin/installer -pkg $(pwd)/MacPorts-2.6.2-10.15-Catalina.pkg -target /
      working-directory: ${{ runner.temp }}
    - run: sudo port install x86_64-elf-binutils
    - run: sudo port install x86_64-elf-gcc
    - run: brew install truncate
    - uses: actions/checkout@v2
    - name: Build kernel.elf
      run: make TOOLPREFIX=x86_64-elf- -j
    - run: brew install qemu
    - name: Unit tests
      run: make QEMUACCEL= qemu-test
