name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build ward.elf
      run: make -j
    - name: Upload ward.elf
      uses: actions/upload-artifact@v1
      with:
        name: ward.elf
        path: output/ward.elf
    - name: Install mtools
      run: sudo apt-get update && sudo apt-get install -y mtools
    - name: Build ward.img
      run: make -j img
    - name: Upload ward.img
      uses: actions/upload-artifact@v1
      with:
        name: ward.img
        path: output/ward.img
    - name: Install QEMU
      run: sudo apt-get install -y qemu-system-x86
    - name: Unit tests
      run: make qemu-test
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install lld
      run: brew install llvm
    - name: Linker version
      run: which ld64.lld
    - name: Build ward.elf
      run: make -j
    - name: Upload ward.elf
      uses: actions/upload-artifact@v1
      with:
        name: ward.elf
        path: output/ward.elf
