name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install lld
      run: sudo apt-get update && sudo apt-get install -y lld
    - name: Build ward.elf
      run: make -j
    - name: Upload ward.elf
      uses: actions/upload-artifact@v1
      with:
        name: ward.elf
        path: output/ward.elf
    - name: Install mtools
      run: sudo apt-get update && sudo apt-get install -y mtools
    - name: Build ward.img
      run: make -j img
    - name: Upload ward.img
      uses: actions/upload-artifact@v1
      with:
        name: ward.img
        path: output/ward.img
    - name: Install QEMU
      run: sudo apt-get install -y qemu-system-x86
    - name: Unit tests
      run: make qemu-test
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew install binutils
        echo "::add-path::/usr/local/opt/binutils/bin"
        echo "::add-path::/usr/local/opt/llvm/bin"
    - name: Build ward.elf
      run: make Q= -j
    - name: Upload ward.elf
      uses: actions/upload-artifact@v1
      with:
        name: ward.elf
        path: output/ward.elf
    - name: Install qemu
      run: brew install qemu
    - name: Test ward.elf
      run: make QEMUSMP=1 qemu-test
